/**
 * FairSight AI — AI Audit Report Component
 * Purple-accented panel rendering the Gemini-generated markdown report.
 * Parses ##-headings into styled sections with animated reveal.
 */

import { Sparkles, Bot, CheckCircle2, AlertTriangle, XCircle } from "lucide-react";

interface AuditReportData {
  report_text: string;
  executive_summary: string;
  model_used: string;
  status: "success" | "fallback";
}

interface AuditReportProps {
  report: AuditReportData;
}

/** Minimal markdown → React renderer for the structured report format. */
function renderMarkdown(text: string) {
  const lines = text.split("\n");
  const elements: React.ReactNode[] = [];
  let key = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.startsWith("## ")) {
      elements.push(
        <h2
          key={key++}
          className="text-base font-bold text-gray-900 mt-6 mb-2 flex items-center gap-2 border-b border-gray-100 pb-1"
        >
          {line.replace("## ", "")}
        </h2>
      );
    } else if (line.startsWith("### ")) {
      const heading = line.replace("### ", "");
      const severity = heading.includes("— FAIL")
        ? "FAIL"
        : heading.includes("— WARN")
          ? "WARN"
          : heading.includes("— PASS")
            ? "PASS"
            : null;

      const badge = severity ? (
        <span
          className={`ml-2 inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full font-semibold ${severity === "PASS"
              ? "bg-green-100 text-green-700"
              : severity === "WARN"
                ? "bg-yellow-100 text-yellow-700"
                : "bg-red-100 text-red-700"
            }`}
        >
          {severity === "PASS" ? (
            <CheckCircle2 className="w-3 h-3" />
          ) : severity === "WARN" ? (
            <AlertTriangle className="w-3 h-3" />
          ) : (
            <XCircle className="w-3 h-3" />
          )}
          {severity}
        </span>
      ) : null;

      const cleanHeading = heading
        .replace(" — FAIL", "")
        .replace(" — WARN", "")
        .replace(" — PASS", "");

      elements.push(
        <h3
          key={key++}
          className="text-sm font-semibold text-gray-800 mt-4 mb-1 flex items-center flex-wrap gap-1"
        >
          {cleanHeading}
          {badge}
        </h3>
      );
    } else if (/^\d+\.\s/.test(line)) {
      // Numbered list item
      elements.push(
        <li
          key={key++}
          className="text-sm text-gray-700 leading-relaxed ml-4 list-decimal"
        >
          {parseBold(line.replace(/^\d+\.\s/, ""))}
        </li>
      );
    } else if (line.startsWith("- ")) {
      elements.push(
        <li
          key={key++}
          className="text-sm text-gray-700 leading-relaxed ml-4 list-disc"
        >
          {parseBold(line.replace("- ", ""))}
        </li>
      );
    } else if (line.trim() === "") {
      elements.push(<div key={key++} className="h-1" />);
    } else {
      elements.push(
        <p key={key++} className="text-sm text-gray-700 leading-relaxed">
          {parseBold(line)}
        </p>
      );
    }
  }

  return elements;
}

/** Convert **bold** text to <strong> */
function parseBold(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return <strong key={i}>{part.slice(2, -2)}</strong>;
    }
    return part;
  });
}

export function AuditReport({ report }: AuditReportProps) {
  return (
    <div className="bg-white rounded-xl border border-purple-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-indigo-600 px-6 py-4 flex items-center gap-3">
        <div className="w-8 h-8 rounded-lg bg-white/20 flex items-center justify-center">
          <Sparkles className="w-4 h-4 text-white" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-white">AI Audit Report</h3>
          <p className="text-xs text-purple-200">
            Generated by {report.model_used === "fallback" ? "Template Engine" : "Google Gemini"}
            {report.status === "fallback" && (
              <span className="ml-2 bg-yellow-400/30 text-yellow-100 rounded px-1.5 py-0.5 text-xs">
                Offline Mode
              </span>
            )}
          </p>
        </div>
        <Bot className="ml-auto w-5 h-5 text-white/60" />
      </div>

      {/* Executive Summary */}
      {report.executive_summary && (
        <div className="px-6 py-4 bg-purple-50 border-b border-purple-100">
          <p className="text-xs font-semibold text-purple-600 uppercase tracking-wide mb-1">
            Executive Summary
          </p>
          <p className="text-sm text-gray-700 leading-relaxed">
            {report.executive_summary}
          </p>
        </div>
      )}

      {/* Full Report */}
      <div className="px-6 py-5">
        <div className="prose prose-sm max-w-none">
          {renderMarkdown(report.report_text)}
        </div>
      </div>
    </div>
  );
}